### ISSUE TITLE
Leveling Skills

### ISSUE THREAD

**Issue by ransananes** [iw2d/kinoko#10]
Seems like you can't level up skills as they're either "not owned by user" or "master level 0/0",

Edit : I might be wrong but I think it is not working due to no job advancements quests to teach the skills and save it into the database(?)

**Comment by iw2d** [comment]
Could you also include steps on reproducing the problem? So that I can try it out on my end and confirm :>

**Comment by ransananes** [comment]
> Could you also include steps on reproducing the problem? So that I can try it out on my end and confirm :>

Just any job, !job 100, and use !levelup 15 (any number would be ok), then try adding sp to first job :)

btw great job on this, one of the cleanest sources out there 💯

**Comment by iw2d** [comment]
Thanks!
I believe this is just an issue with the !job command. I probably missed this because I was always using the !max command along with it to get all the skills.
