### ISSUE TITLE
[bug] infinity effect and buff icon's shadow

### ISSUE THREAD

**Issue by leevccc** [iw2d/kinoko#12]
1. use infinity not improve matk

2. buff icon error

in `handleInfinity` func

```
user.setTemporaryStat(CharacterTemporaryStat.Infinity, option.update(option.nOption + damage));
```

will announce client to refresh buff icon, that cause the infinity buff icon's shadow reset to no shadow

I think it is only necessary to handle the changes in hp and mp, and there is no need to notify the client again, because it has already been notified when the skill is used.

**Comment by iw2d** [comment]
1. The Infinity CTS is used directly in the damage calculation - you will not see any changes in the stat window, but the damage will be increased.
2. The v95 client doesn't seem to have a way to update the temporary stat without resetting the shadow. I have confirmed this limitation through experiments and old videos (with hero's combo attack buff), but if you can find a counterexample I will gladly take another look.

**Comment by leevccc** [comment]
thanks for your reply, let me try to hook client

**Comment by leevccc** [comment]
i found some reason
![8a9fa2091d6b7bbeefe6cbd51a3940e3](https://github.com/user-attachments/assets/479e9952-d6e8-4b6b-bbfe-f548cb0191ee)

look there the timeUnit changed, which cause shadow incorrect

Although I haven't found out what caused the timeUnit to change, I plan to rewrite a set of formulas here and introduce the buff countdown. In this way, I won't need this variable.

Report this issue to you, thank you for your open source code.
