### ISSUE TITLE
bug npc shop

### ISSUE THREAD

**Issue by leevccc** [iw2d/kinoko#24]
ShopDialog.java

in case Buy

`if (!im.canAddItem(itemId, count)) {`

and

`final Item boughtItem = ii.createItem(user.getNextItemSn(), rechargeable ? ii.getSlotMax() : count);`

count should be replace of `quantity`

`int quantity = count * shopItem.getQuantity();`

**Comment by leevccc** [comment]
for example

set a item sell x2000 for 1 mesos

player buy 1 (count)

he cose 1mesos, but get only 1 (count), actually, he should get 1 x 2000

**Comment by iw2d** [comment]
Good find, I missed this because the BMS shop data didn't have any bundled items.
Thanks.
